[features]
seeds = true
[programs.localnet]
crypton = "FhrLHiXwBVmXGDLSF5hQVxmsn1bL1bEgMyT5nrSenyd5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/icus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
